language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
jobs:
  include:
    - python: 3.8
      install: make install
      script: make ci
before_install:
  - pip install poetry
install:
  - poetry build
  - pip install dist/*.tar.gz
  - pip install pytest
script:
  - pytest tests

